


#define _EXT_FUNC __declspec( dllexport )


extern "C" _EXT_FUNC void _stdcall START_UP(void) ;
extern "C" _EXT_FUNC void _stdcall TRIGGER_RF(void) ;
extern "C" _EXT_FUNC void _stdcall RF_5841_INIT(void) ;
extern "C" _EXT_FUNC void _stdcall RF_5830_INIT(void) ;
extern "C" _EXT_FUNC void _stdcall RF_GAIN(void) ;
extern "C" _EXT_FUNC void _stdcall RF_EVM_4MS(void) ;
extern "C" _EXT_FUNC void _stdcall RF_EVM_280US(void) ;
